### PR TITLE
Fix replays that can't be parsed

### LINKED ISSUE #6: Unprocessable replays
I've been running Octane against around half of the replays which have been uploaded to Rocket League Replays tonight. Of the ~26,000 I've tested, 105 (0.4%) came back with errors of some variety.  I've collated them below, grouped by the exception message.

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:Owner"`
- https://www.rocketleaguereplays.com/replays/5390/
- https://www.rocketleaguereplays.com/replays/3540/
- https://www.rocketleaguereplays.com/replays/53420/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:Base"`
- https://www.rocketleaguereplays.com/replays/29321/
- https://www.rocketleaguereplays.com/replays/7225/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:RelativeLocation"`
- https://www.rocketleaguereplays.com/replays/34030/
- https://www.rocketleaguereplays.com/replays/24364/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.TeamInfo:TeamName"`
- https://www.rocketleaguereplays.com/replays/15515/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.TeamInfo:TeamIndex"`
- https://www.rocketleaguereplays.com/replays/17813/

`>>> octane-0.6.2-osx: could not find class for object id <int>`
- https://www.rocketleaguereplays.com/replays/54141/
- https://www.rocketleaguereplays.com/replays/43809/
- https://www.rocketleaguereplays.com/replays/43811/
- https://www.rocketleaguereplays.com/replays/43824/
- https://www.rocketleaguereplays.com/replays/43861/
- https://www.rocketleaguereplays.com/replays/43984/
- https://www.rocketleaguereplays.com/replays/43985/
- https://www.rocketleaguereplays.com/replays/43986/
- https://www.rocketleaguereplays.com/replays/48722/
- https://www.rocketleaguereplays.com/replays/54137/
- https://www.rocketleaguereplays.com/replays/7850/

`>>> octane-0.6.2-osx: parsing previous frame probably failed. time: 1.597e-42, delta: 2.7500482`
- https://www.rocketleaguereplays.com/replays/54859/
- https://www.rocketleaguereplays.com/replays/39988/
- https://www.rocketleaguereplays.com/replays/39992/
- https://www.rocketleaguereplays.com/replays/39833/
- https://www.rocketleaguereplays.com/replays/54859/
- https://www.rocketleaguereplays.com/replays/39996/
- https://www.rocketleaguereplays.com/replays/39994/
- https://www.rocketleaguereplays.com/replays/41001/
- https://www.rocketleaguereplays.com/replays/39991/
- https://www.rocketleaguereplays.com/replays/39990/
- https://www.rocketleaguereplays.com/replays/39989/
- https://www.rocketleaguereplays.com/replays/39987/
- https://www.rocketleaguereplays.com/replays/39993/
- https://www.rocketleaguereplays.com/replays/39860/
- https://www.rocketleaguereplays.com/replays/39088/
- https://www.rocketleaguereplays.com/replays/39087/
- https://www.rocketleaguereplays.com/replays/39862/
- https://www.rocketleaguereplays.com/replays/32791/
- https://www.rocketleaguereplays.com/replays/32792/
- https://www.rocketleaguereplays.com/replays/28619/
- https://www.rocketleaguereplays.com/replays/27199/
- https://www.rocketleaguereplays.com/replays/30546/
- https://www.rocketleaguereplays.com/replays/30818/
- https://www.rocketleaguereplays.com/replays/30822/
- https://www.rocketleaguereplays.com/replays/28560/
- https://www.rocketleaguereplays.com/replays/28167/
- https://www.rocketleaguereplays.com/replays/17993/
- https://www.rocketleaguereplays.com/replays/17995/
- https://www.rocketleaguereplays.com/replays/18000/
- https://www.rocketleaguereplays.com/replays/17998/
- https://www.rocketleaguereplays.com/replays/17999/
- https://www.rocketleaguereplays.com/replays/32658/
- https://www.rocketleaguereplays.com/replays/17899/
- https://www.rocketleaguereplays.com/replays/26470/
- https://www.rocketleaguereplays.com/replays/3070/

`>>> octane-0.6.2-osx: the unknown flag in a new replication is true! what does it mean?`
- https://www.rocketleaguereplays.com/replays/39698/
- https://www.rocketleaguereplays.com/replays/39697/
- https://www.rocketleaguereplays.com/replays/47109/
- https://www.rocketleaguereplays.com/replays/39316/
- https://www.rocketleaguereplays.com/replays/39317/
- https://www.rocketleaguereplays.com/replays/39315/
- https://www.rocketleaguereplays.com/replays/38837/
- https://www.rocketleaguereplays.com/replays/38831/
- https://www.rocketleaguereplays.com/replays/38839/
- https://www.rocketleaguereplays.com/replays/38835/
- https://www.rocketleaguereplays.com/replays/38836/
- https://www.rocketleaguereplays.com/replays/38832/
- https://www.rocketleaguereplays.com/replays/38834/
- https://www.rocketleaguereplays.com/replays/38833/
- https://www.rocketleaguereplays.com/replays/38838/
- https://www.rocketleaguereplays.com/replays/38247/
- https://www.rocketleaguereplays.com/replays/38248/
- https://www.rocketleaguereplays.com/replays/38042/
- https://www.rocketleaguereplays.com/replays/38040/
- https://www.rocketleaguereplays.com/replays/38039/
- https://www.rocketleaguereplays.com/replays/38041/
- https://www.rocketleaguereplays.com/replays/38043/
- https://www.rocketleaguereplays.com/replays/34060/
- https://www.rocketleaguereplays.com/replays/34187/
- https://www.rocketleaguereplays.com/replays/32483/
- https://www.rocketleaguereplays.com/replays/32482/
- https://www.rocketleaguereplays.com/replays/30846/
- https://www.rocketleaguereplays.com/replays/29322/
- https://www.rocketleaguereplays.com/replays/29323/
- https://www.rocketleaguereplays.com/replays/29318/
- https://www.rocketleaguereplays.com/replays/32637/
- https://www.rocketleaguereplays.com/replays/30528/
- https://www.rocketleaguereplays.com/replays/30529/
- https://www.rocketleaguereplays.com/replays/30526/
- https://www.rocketleaguereplays.com/replays/33564/
- https://www.rocketleaguereplays.com/replays/29319/
- https://www.rocketleaguereplays.com/replays/27967/
- https://www.rocketleaguereplays.com/replays/41188/
- https://www.rocketleaguereplays.com/replays/30556/
- https://www.rocketleaguereplays.com/replays/41189/
- https://www.rocketleaguereplays.com/replays/38972/
- https://www.rocketleaguereplays.com/replays/29847/
- https://www.rocketleaguereplays.com/replays/28166/
- https://www.rocketleaguereplays.com/replays/18303/
- https://www.rocketleaguereplays.com/replays/16779/
- https://www.rocketleaguereplays.com/replays/16745/
- https://www.rocketleaguereplays.com/replays/42163/
- https://www.rocketleaguereplays.com/replays/16242/
- https://www.rocketleaguereplays.com/replays/16088/
- https://www.rocketleaguereplays.com/replays/16046/

### PR DESCRIPTION
**Pull request by tfausak**
This will fix #6. It's still a work in progress. Debugging these problems is annoying, to say the least. 
- [x] don't know how to read property "Engine.Actor:Owner"
  - 5e08e127c27557152647f9f89327ba36ba758394
- [ ] don't know how to read property "Engine.Actor:Base"
- [x] don't know how to read property "Engine.Actor:RelativeLocation"
  - 182cb7a5fab7f47cea6bf66d3a1f806d4806d376
- [ ] don't know how to read property "Engine.TeamInfo:TeamName"
  - You would think this would be a string, but that doesn't work. 
- [x] don't know how to read property "Engine.TeamInfo:TeamIndex"
  - 3ec472037651d403c1d4243951055eadc7b27bc1
- [x] could not find class for object id _X_
  - 56bfae556f354ca45f78d5c31c785af34d8b56fa
  - 6244ed6924c2471798d8047f07628f2b96003d98
  - 3805f00920ec6817dfec80fe46626f66b3c2b6c8
- [ ] parsing previous frame probably failed. time: _X_, delta: _Y_
- [ ] the unknown flag in a new replication is true! what does it mean?

### CODE REVIEW

**Comment by tfausak** [comment]
I think most of the remaining failures come from parsing `TAGame.PRI_TA:ReplicatedGameEvent` incorrectly. Every replication looks fine until it runs into one of those properties with one of these values:

```
("TAGame.PRI_TA:ReplicatedGameEvent",PFlaggedInt False (-939392980))
("TAGame.PRI_TA:ReplicatedGameEvent",PFlaggedInt False 939655180)
```

**Comment by tfausak** [comment]
Those integer values correspond to these hex/binary values:

```
 0x34004013
 0b00110100000000000100000000010011

 0x3000401c
 0b00110000000000000100000000011100
```

_Usually_ the flag on the replicated game events is true. Sometimes it's false and the value is `-1` (`0xffffffff`).

**Comment by tfausak** [comment]
As this tries to parse a replay, I see a lot of properties that I haven't seen before.
- Engine.Actor:Velocity
- Engine.PlayerReplicationInfo:ClientFillRemoteUserData
- Engine.PlayerReplicationInfo:ServerUpdateRemoteUserData
- TAGame.PRI_TA:ClientNotifyGainedStat
- TAGame.PRI_TA:RespawnTimeRemaining
- TAGame.PRI_TA:ServerSetCameraSettings
- TAGame.PRI_TA:ServerSetPartyLeader
- TAGame.PRI_TA:ServerSetUsingBehindView
- TAGame.PRI_TA:ServerSpectate
- TAGame.PRI_TA:ServerVoteToForfeit
- TAGame.PRI_TA:SkillTier

I doubt all (or even many) of these are actually replicated, but I don't know how to parse any of them. Lots of "server set" stuff in there.

**Comment by tfausak** [comment]
I was able to reproduce some of these problems by starting a new local exhibition match with no bots, touching the ball, and then switching to spectator. I'm guessing there aren't many replays with replicated spectator information.

**Comment by tfausak** [comment]
I have been looking at [this replay](https://www.rocketleaguereplays.com/replays/0b83f380-446c-24dd-7ca5-298ce4434013/). By varying the `BITS` environment variable, I can see a few promising number of bits to read.

| Bits | Next property name |
| --- | --- |
| 2 | Engine.Actor:Velocity |
| 16 | TAGame.PRI_TA:ServerSetUsingFreecam |
| 32 | Engine.Actor:bNetOwner |
| 44 | TAGame.PRI_TA:ServerSetUsingFreecam |
| 48 | TAGame.PRI_TA:ServerSpectate |
| 56 | TAGame.PRI_TA:ServerSpectate |
| 57 | Engine.PlayerReplicationInfo:ServerUpdateRemoteUserData |
| 70 | TAGame.PRI_TA:RespawnTimeRemaining |
| 71 | Engine.PlayerReplicationInfo:bFromPreviousLevel |
| 72 | TAGame.PRI_TA:ServerSetUsingFreecam |
| 73 | TAGame.PRI_TA:ServerVoteToForfeit |
| 76 | Engine.Actor:Base |
| 112 | TAGame.PRI_TA:ServerVoteToForfeit |
| 113 | TAGame.PRI_TA:SkillTier |
| 120 | TAGame.PRI_TA:ServerSetPartyLeader |
| 129 | Engine.PlayerReplicationInfo:ClientFillRemoteUserData |
| 165 | TAGame.PRI_TA:ClientNotifyGainedStat |
| 167 | Engine.Actor:RemoteRole |

I added the boolean properties in d4e72a2783680d165ade9050c859a7e8a01ac309, but that didn't successfully parse the frame. I made some notes on attempting to parse some of the other properties:

---

TAGame.PRI_TA:ServerSetUsingFreecam
- maybe enum? 510 or 512
- maybe flagged int? next prop is skill tier
- maybe float? next prop is vote to forfeit
- maybe int? next prop is vote to forfeit

Engine.Actor:Velocity
- ignoring for now

TAGame.PRI_TA:ServerVoteToForfeit
- maybe enum? always 517
- nothing else makes sense... probably not the right thing to read

TAGame.PRI_TA:SkillTier
- maybe enum? also always 517
- nothing else makes sense... but frame parsing fails

**Comment by tfausak** [comment]
I didn't notice at first, but reading 74 bits actually parses one replication successfully. Then it fails on some subsequent one.

```
read 74 bits and got 0b01101000000000001000000000100110100100000000111010010111111110011111111111
read 74 bits and got 0b00000000000110000000010000000110001011000000101011001111100000000000000000
octane: parsing previous frame probably failed. time: 1.213e-41, delta: 1.213e-41
```

**Comment by danielsamuels** [comment]
I'm not sure if you're doing this already, but any time you see a property like `Engine.Actor:bNetOwner`, you can be sure it's a boolean value. I actually ended up parsing these types of keys [without actually defining them](https://github.com/rocket-league-replays/pyrope/blob/master/pyrope/netstream_property_parsing.py#L109) in PyRope.

**Comment by tfausak** [comment]
Yup, I got those in d4e72a2783680d165ade9050c859a7e8a01ac309. I prefer to explicitly match every property name that I know of rather than doing some string searching and manipulation. Unfortunately reading the boolean values didn't successfully parse the frame. I think they're a red herring.

**Comment by tfausak** [comment]
I still have some work to do here, but I'm going to go ahead and merge this. I'll keep trying to figure out the rest of these problems in another pull request. No reason to hold up the fixes I have made.

**Pull request merged**
