### PR TITLE
Correctly parse SteamIDs

### LINKED ISSUE #38: Invalid Steam ID being output
I'll preface this by saying that it could just be the replay itself that is wrong, but I thought you'd be interested none-the-less.

On [this](https://www.rocketleaguereplays.com/replays/c9bd8011-4967-696b-a792-e8bd905f8ada/) replay, the player with the name 'Ahad' has a Steam ID set to a value of 24488897, which is not a valid Steam ID.

```
"Engine.PlayerReplicationInfo:UniqueId": {
  "Value": {
    "Remote": {
      "Value": 24488897,
      "Type": "Steam"
    },
    "Local": 0,
    "System": "Steam"
  },
  "Type": "UniqueId"
},
```

Is this a replay error, or a parser issue?

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #38.

### CODE REVIEW

**Comment by tfausak** [comment]
@danielsamuels: Although I was parsing SteamIDs incorrectly, I think this player's SteamID is simply invalid. Here's what this branch says about it:

``` json
"Engine.PlayerReplicationInfo:UniqueId": {
  "Value": {
    "Remote": {
      "Value": {
        "Universe": 0,
        "Type": 0,
        "Number": 24488897,
        "Instance": 0
      },
      "Type": "Steam"
    },
    "Local": 0,
    "System": "Steam"
  },
  "Type": "UniqueId"
},
```

Compare that to "Chupis" from the same replay:

``` json
"Engine.PlayerReplicationInfo:UniqueId": {
  "Value": {
    "Remote": {
      "Value": {
        "Universe": 1,
        "Type": 1,
        "Number": 91355920,
        "Instance": 1
      },
      "Type": "Steam"
    },
    "Local": 0,
    "System": "Steam"
  },
  "Type": "UniqueId"
},
```

**Comment by danielsamuels** [comment]
Hmm, it could be `STEAM_0:1:24488897` which gives you [this user](https://steamcommunity.com/profiles/76561198009243523). Could be a match.

**Comment by tfausak** [comment]
Yeah, that seems more likely than [this guy](http://steamcommunity.com/profiles/76561198009243522).

**Comment by danielsamuels** [comment]
Yup!

**Comment by tfausak** [comment]
That doesn't make a whole lot of sense, though. If the "number" part is correct, how can I be reading everything else as `0` when at least one of them should be `1`?

**Comment by danielsamuels** [comment]
I'm not sure!  May I request that the 64-bit values remain somewhere, if at all possible? I use them for a lot of things, and would _prefer_ not to have to convert them back.

**Comment by tfausak** [comment]
Oh, if you're using the SteamIDs as they are now, I'd prefer to leave them alone. This one particular player's SteamID is bogus, but it's not a parsing problem.

**Comment by danielsamuels** [comment]
Sure, no problem - I just wasn't sure where the problem was.  If it's just bad data in the replay then I can live with that.

**Comment by tfausak** [comment]
Yeah, I'm pretty sure it's not a parser error. Especially since it is serialized many times and is "wrong" every time, but all the other SteamIDs are fine. For some reason that SteamID has three bits as `0` when they should be `1`. 

```
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 0}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x000000000175abc1})) (Just 0x00) (Just "Ahad") (Boolean {unpack = True}) (Boolean {unpack = True})
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 1}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x0110000101214082})) (Just 0x00) (Just "Rayhush") (Boolean {unpack = True}) (Boolean {unpack = True})
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 2}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x0110000102890e3c})) (Just 0x00) (Just "TeRRoR eYeS") (Boolean {unpack = True}) (Boolean {unpack = True})
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 3}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x011000010662c745})) (Just 0x00) (Just "Mo") (Boolean {unpack = True}) (Boolean {unpack = True})
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 4}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x011000010571fb10})) (Just 0x00) (Just "Chupis") (Boolean {unpack = True}) (Boolean {unpack = True})
"ProjectX.GRI_X:Reservations" => VReservation (CompressedWord {limit = 7, value = 5}) 0x01 (RemoteSteamId (SteamId {unpackSteamId = 0x01100001043246fb})) (Just 0x00) (Just "rosellemark") (Boolean {unpack = True}) (Boolean {unpack = True})
```

**Pull request closed without merging**
