### PR TITLE
Read unsigned integers for byte properties

### LINKED ISSUE #2: Invalid data being returned for TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount
I've been integrating Octane into Rocket League Replays using [this replay](https://www.rocketleaguereplays.com/replays/065d86a7-4dfa-a7ed-9a3c-159915525bc8/) as my test replay.  My constraint checks are currently failing on values stored within `TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount`. These values should be in the range of 0-255, but I'm seeing numbers in a far broader range. Here's a small snapshot:

```
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 114,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -112,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -112,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:Vehicle': {'contents': [True, 79],
                                    'tag': 'PFlaggedInt'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 82,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 2, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 29,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 0,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 8, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 112,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 112,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 2, 'tag': 'PByte'},
 'TAGame.CarComponent_TA:Vehicle': {'contents': [True, 79],
                                    'tag': 'PFlaggedInt'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 29,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 85,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 4, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -1,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': 14,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 10, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -1,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -62,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 6, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -1,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 10, 'tag': 'PByte'},
 'TAGame.CarComponent_TA:Vehicle': {'contents': [True, 38],
                                    'tag': 'PFlaggedInt'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -62,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 6, 'tag': 'PByte'},
 'TAGame.CarComponent_TA:Vehicle': {'contents': [True, 79],
                                    'tag': 'PFlaggedInt'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -79,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 8, 'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -50,
                                                        'tag': 'PByte'}}
{'TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount': {'contents': -72,
                                                        'tag': 'PByte'},
 'TAGame.CarComponent_TA:ReplicatedActive': {'contents': 12, 'tag': 'PByte'}}
```

Are these perhaps relative values rather than absolute, or is it just a bug?

### PR DESCRIPTION
**Pull request by tfausak**
This fixes #2.

### CODE REVIEW

**Comment by tfausak** [comment]
@danielsamuels: If you happen to have [Stack](http://docs.haskellstack.org/en/stable/README/) set up, you can test against this branch. 

``` sh
git clone git@github.com:tfausak/octane.git
git checkout -t origin/gh-2-byte-properties
stack setup
stack build
stack exec octane path/to-the.replay | python -m json.tool | less
```

Otherwise I'll merge this into master and release a new version. It usually takes about an hour to build the executables.

**Comment by danielsamuels** [comment]
I'll test it now and let you know the results.

**Comment by danielsamuels** [comment]
Perfect, the data matches what I'm seeing on the live server. Thanks for the quick turnaround!

**Comment by tfausak** [comment]
No problem, happy to help! I'm happy to fix any other discrepancies with RLR.

**Pull request merged**
